package com.dsar.domain;

public enum AuditAction {
  REQUEST_CREATED,
  STATUS_CHANGED,
  ASSIGNED,
  ATTACHMENT_UPLOADED,
  ATTACHMENT_REDACTED,
  EXPORT_COMPILED,
  NOTIFICATION_SENT,
  NOTE_ADDED,
  REQUEST_COMPLETED,
  REQUEST_REJECTED
}
